// Code generated by spec-gen. DO NOT EDIT.
package download

import (
	"github.com/michaeldcanady/go-onedrive/internal/core/di"
	"github.com/spf13/cobra"
)

// CreateDownloadCmd returns a new [cobra.Command] initialized with dependencies
// and configured to execute the "download" operation.
func CreateDownloadCmd(container di.Container) *cobra.Command {
	var opts Options
	var c *CommandContext

	l := container.Logger().With("command", "download")

	// Create the handler using the generated factory
	var handler Handler = NewCommand(
		container.VFS(),
		container.Profile(),
		container.Logger(),
		l,
		container.Resolver(),
	)

	cmd := &cobra.Command{
		Use:   "download <source> <destination> [flags]",
		Short: "Download files and directories",
		Args:  cobra.ExactArgs(2),
		PreRunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 {
				opts.Source = args[0]
			}
			if len(args) > 1 {
				opts.Destination = args[1]
			}
			opts.Stdout = cmd.OutOrStdout()
			opts.Stderr = cmd.ErrOrStderr()

			c = &CommandContext{
				Ctx:     cmd.Context(),
				Options: opts,
			}

			if err := handler.Validate(c); err != nil {
				return err
			}

			return handler.Resolve(c)
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := handler.Execute(c); err != nil {
				return err
			}
			return handler.Finalize(c)
		},
	}
	cmd.Flags().BoolVarP(&opts.Recursive, "recursive", "r", false, "Download directories recursively")

	return cmd
}
