// Code generated by spec-gen. DO NOT EDIT.
package download

import (
	"io"
)

// Options encapsulates all user-provided arguments and flags for the command.
type Options struct {
	Source string // The remote path on OneDrive.
	Destination string // The local path where the item should be downloaded.
	Recursive bool // Download directories recursively

	// Stdout receives standard output messages.
	Stdout io.Writer
	// Stderr receives error and diagnostic messages.
	Stderr io.Writer
}
