// Code generated by spec-gen. DO NOT EDIT.
package login

import (
	"github.com/michaeldcanady/go-onedrive/internal/core/di"
	"github.com/spf13/cobra"
)

// CreateLoginCmd returns a new [cobra.Command] initialized with dependencies
// and configured to execute the "login" operation.
func CreateLoginCmd(container di.Container) *cobra.Command {
	var opts Options
	var c *CommandContext

	l := container.Logger().With("command", "identity-login")
	
	// Create the handler using the generated factory
	var handler Handler = NewCommand(
		container.Config(),
		container.Identity(),
		container.Token(),
		container.Profile(),
		container.Logger(),
		l,
		container.Resolver(),
	)

	cmd := &cobra.Command{
		Use:   "login [flags]",
		Short: "Authenticate with an identity provider",
		Long:  `Authenticate with a cloud provider (Azure, Google) using various methods (Interactive, Device Code, Service Principal).
You can specify the provider and method via flags or in your configuration.
`,
		PreRunE: func(cmd *cobra.Command, args []string) error {
			opts.Stdout = cmd.OutOrStdout()
			opts.Stderr = cmd.ErrOrStderr()

			c = &CommandContext{
				Ctx:     cmd.Context(),
				Options: opts,
			}

			if err := handler.Validate(c); err != nil {
				return err
			}

			return handler.Resolve(c)
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := handler.Execute(c); err != nil {
				return err
			}
			return handler.Finalize(c)
		},
	}
	cmd.Flags().StringVar(&opts.Provider, "provider", "azure", "The identity provider to use (e.g., azure, google)")
	cmd.Flags().StringVar(&opts.Id, "id", "", "The specific identity (email) to authenticate")
	cmd.Flags().StringVar(&opts.Alias, "alias", "", "An optional human-friendly name for this identity")
	cmd.Flags().BoolVar(&opts.ShowToken, "show-token", false, "Display the access token after login")
	cmd.Flags().BoolVarP(&opts.Force, "force", "f", false, "Force re-authentication even if a valid profile exists")
	cmd.Flags().StringVar(&opts.Method, "method", "", "Authentication method (interactive, device-code, client-secret, environment)")
	cmd.Flags().StringVar(&opts.TenantId, "tenant-id", "", "Azure AD tenant ID (Azure only)")
	cmd.Flags().StringVar(&opts.ClientId, "client-id", "", "Client ID for the application")
	cmd.Flags().StringVar(&opts.ClientSecret, "client-secret", "", "Client secret for the application")
	cmd.Flags().StringVar(&opts.Scopes, "scopes", "", "Comma-separated list of scopes to request")

	return cmd
}
