// Code generated by spec-gen. DO NOT EDIT.
package rm

import (
	"context"
	"fmt"
	"github.com/michaeldcanady/go-onedrive/internal/core/logger"
	"github.com/michaeldcanady/go-onedrive/internal/core/resolver"
	"github.com/michaeldcanady/go-onedrive/internal/features/profile"
	"github.com/michaeldcanady/go-onedrive/internal/features/vfs"
)

// CommandContext carries the execution state and parsed options for a command.
type CommandContext struct {
	Ctx     context.Context
	Options Options
}

// Handler coordinates the lifecycle of a CLI command execution.
type Handler interface {
	// Validate performs initial checks on the provided options.
	Validate(ctx *CommandContext) error

	// Resolve translates raw user input (like paths or IDs) into domain entities.
	Resolve(ctx *CommandContext) error

	// Execute performs the primary business logic of the command.
	Execute(ctx *CommandContext) error

	// Finalize handles any post-execution cleanup or output formatting.
	Finalize(ctx *CommandContext) error
}

// Command provides a base implementation for command handlers, injected with required services.
type Command struct {
	fS       vfs.VFS
	profile  profile.Service
	logger   logger.Service
	l        logger.Service
	resolver resolver.Service
}

// NewCommand creates a new instance of the rm command handler.
func NewCommand(
	fS vfs.VFS,
	profile profile.Service,
	logger logger.Service,
	l logger.Service,
	r resolver.Service,
) *Command {
	return &Command{
		fS:       fS,
		profile:  profile,
		logger:   logger,
		l:        l,
		resolver: r,
	}
}

// BaseResolve handles the resolution of command arguments and flags based on the specification.
func (c *Command) BaseResolve(ctx *CommandContext) error {
	if ctx.Options.Path != "" {
		resolved, err := c.resolver.ResolvePath(ctx.Ctx, ctx.Options.Path)
		if err != nil {
			return fmt.Errorf("failed to resolve path %s: %w", ctx.Options.Path, err)
		}
		ctx.Options.Path = resolved
	}

	return nil
}
