// Code generated by spec-gen. DO NOT EDIT.
package list

import (
	"github.com/michaeldcanady/go-onedrive/internal/core/di"
	"github.com/spf13/cobra"
)

// CreateListCmd returns a new [cobra.Command] initialized with dependencies
// and configured to execute the "list" operation.
func CreateListCmd(container di.Container) *cobra.Command {
	var opts Options
	var c *CommandContext

	l := container.Logger().With("command", "drive-list")
	
	// Create the handler using the generated factory
	var handler Handler = NewCommand(
		container.Drive(),
		container.Mounts(),
		container.Mounts(),
		container.Profile(),
		container.Formatter(),
		container.Logger(),
		l,
		container.Resolver(),
	)

	cmd := &cobra.Command{
		Use:   "list [flags]",
		Short: "List all available storage drives",
		Long:  `Retrieve all storage drives associated with your authenticated accounts, distinguishing between mounted and unmounted drives.`,
		PreRunE: func(cmd *cobra.Command, args []string) error {
			opts.Stdout = cmd.OutOrStdout()
			opts.Stderr = cmd.ErrOrStderr()

			c = &CommandContext{
				Ctx:     cmd.Context(),
				Options: opts,
			}

			if err := handler.Validate(c); err != nil {
				return err
			}

			return handler.Resolve(c)
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := handler.Execute(c); err != nil {
				return err
			}
			return handler.Finalize(c)
		},
	}
	cmd.Flags().StringVar(&opts.Id, "id", "", "The specific identity (email or alias) to list drives for")
	cmd.Flags().StringVarP(&opts.Format, "format", "o", "table", "Output format (table, json, yaml)")
	cmd.Flags().BoolVarP(&opts.All, "all", "a", false, "Show all drives, including those not currently mounted")

	return cmd
}
