// Code generated by spec-gen. DO NOT EDIT.
package list

import (
	"io"
)

// Options encapsulates all user-provided arguments and flags for the command.
type Options struct {
	Id string // The specific identity (email or alias) to list drives for
	Format string // Output format (table, json, yaml)
	All bool // Show all drives, including those not currently mounted

	// Stdout receives standard output messages.
	Stdout io.Writer
	// Stderr receives error and diagnostic messages.
	Stderr io.Writer
}
