"component: go":
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "**/*.go"
              - "go.mod"
              - "go.sum"

"component: doc":
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "docs/*"
              - "**/*.md"

"component: ci":
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - ".github/workflows/**"

"type: bug":
  - any:
      - head-branch:
          - "^bug"

"type: chore":
  - any:
      - head-branch:
          - "^chore"

"type: task":
  - any:
      - head-branch:
          - "^feature"
