# ============================================
# COMPONENT LABELS
# ============================================

"component: go":
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "**/*.go"
              - "!internal*/*/auth/**/*.go"
              - "!internal*/*/common/**/*.go"
              - "!internal*/*/fs/**/*.go"
              - "!internal*/*/file/**/*.go"
              - "!internal*/*/profile/**/*.go"
              - "!internal*/*/state/**/*.go"
              - "!internal*/*/cache/**/*.go"

"component: auth":
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "internal*/*/auth/**/*.go"

"component: common":
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "internal*/*/common/**/*.go"

"component: filesystem":
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "internal*/*/fs/**/*.go"
              - "internal*/*/file/**/*.go"

"component: profile":
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "internal*/*/profile/**/*.go"

"component: state":
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "internal*/*/state/**/*.go"

"component: cache":
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "internal*/*/cache/**/*.go"

"component: doc":
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "docs/**"
              - "**/*.md"

"component: ci":
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - ".github/workflows/**"

# ============================================
# TYPE LABELS
# ============================================

"type: bug":
  - any:
      - head-branch:
          - "^bug"

"type: chore":
  - any:
      - head-branch:
          - "^chore"

"type: task":
  - any:
      - head-branch:
          - "^feature"
