// Code generated by spec-gen. DO NOT EDIT.
package edit

import (
	"github.com/michaeldcanady/go-onedrive/internal/core/di"
	"github.com/spf13/cobra"
)

// CreateEditCmd returns a new [cobra.Command] initialized with dependencies
// and configured to execute the "edit" operation.
func CreateEditCmd(container di.Container) *cobra.Command {
	var opts Options
	var c *CommandContext

	l := container.Logger().With("command", "edit")
	
	// Create the handler using the generated factory
	var handler Handler = NewCommand(
		container.VFS(),
		container.Profile(),
		container.Editor(),
		container.Logger(),
		l,
		container.Resolver(),
	)

	cmd := &cobra.Command{
		Use:   "edit <path> [flags]",
		Short: "Edit a file",
		Long:  `Open a file in your default editor. Changes are synced back when the editor closes.`,
		Args:  cobra.ExactArgs(1),
		PreRunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 {
				opts.Path = args[0]
			}
			opts.Stdout = cmd.OutOrStdout()
			opts.Stderr = cmd.ErrOrStderr()

			c = &CommandContext{
				Ctx:     cmd.Context(),
				Options: opts,
			}

			if err := handler.Validate(c); err != nil {
				return err
			}

			return handler.Resolve(c)
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := handler.Execute(c); err != nil {
				return err
			}
			return handler.Finalize(c)
		},
	}
	cmd.Flags().StringVar(&opts.Editor, "editor", "", "Editor to use (overrides config and environment)")
	cmd.Flags().BoolVar(&opts.Force, "force", false, "Force upload even if the remote file has changed")

	return cmd
}
