// Code generated by spec-gen. DO NOT EDIT.
package remove

import (
	"io"
)

// Options encapsulates all user-provided arguments and flags for the command.
type Options struct {
	Path string // The path of the mount point to remove.

	// Stdout receives standard output messages.
	Stdout io.Writer
	// Stderr receives error and diagnostic messages.
	Stderr io.Writer
}
