// Code generated by spec-gen. DO NOT EDIT.
package cp

import (
	"io"
)

// Options encapsulates all user-provided arguments and flags for the command.
type Options struct {
	Source string // The path to the item to copy.
	Destination string // The path where the item should be copied.
	Recursive bool // Copy directories recursively

	// Stdout receives standard output messages.
	Stdout io.Writer
	// Stderr receives error and diagnostic messages.
	Stderr io.Writer
}
