// Code generated by spec-gen. DO NOT EDIT.
package list

import (
	"github.com/michaeldcanady/go-onedrive/internal/core/di"
	"github.com/spf13/cobra"
)

// CreateListCmd returns a new [cobra.Command] initialized with dependencies
// and configured to execute the "list" operation.
func CreateListCmd(container di.Container) *cobra.Command {
	var opts Options
	var c *CommandContext

	l := container.Logger().With("command", "identity-list")

	// Create the handler using the generated factory
	var handler Handler = NewCommand(
		container.Identity(),
		container.Profile(),
		container.Formatter(),
		container.Logger(),
		l,
		container.Resolver(),
	)

	cmd := &cobra.Command{
		Use:   "list [flags]",
		Short: "List all authenticated identities",
		Long: `List all authenticated identities managed by the host.
This includes identities from all configured identity providers.
`,
		PreRunE: func(cmd *cobra.Command, args []string) error {
			opts.Stdout = cmd.OutOrStdout()
			opts.Stderr = cmd.ErrOrStderr()

			c = &CommandContext{
				Ctx:     cmd.Context(),
				Options: opts,
			}

			if err := handler.Validate(c); err != nil {
				return err
			}

			return handler.Resolve(c)
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := handler.Execute(c); err != nil {
				return err
			}
			return handler.Finalize(c)
		},
	}
	cmd.Flags().StringVarP(&opts.Format, "format", "o", "table", "Output format (table, json, yaml)")

	return cmd
}
