// Code generated by spec-gen. DO NOT EDIT.
package list

import (
	"io"
)

// Options encapsulates all user-provided arguments and flags for the command.
type Options struct {
	Format string // Output format (table, json, yaml)

	// Stdout receives standard output messages.
	Stdout io.Writer
	// Stderr receives error and diagnostic messages.
	Stderr io.Writer
}
