// Code generated by spec-gen. DO NOT EDIT.
package mv

import (
	"io"
)

// Options encapsulates all user-provided arguments and flags for the command.
type Options struct {
	Source      string // The current path of the item.
	Destination string // The new path of the item.

	// Stdout receives standard output messages.
	Stdout io.Writer
	// Stderr receives error and diagnostic messages.
	Stderr io.Writer
}
