// Code generated by spec-gen. DO NOT EDIT.
package logout

import (
	"github.com/michaeldcanady/go-onedrive/internal/core/di"
	"github.com/spf13/cobra"
)

// CreateLogoutCmd returns a new [cobra.Command] initialized with dependencies
// and configured to execute the "logout" operation.
func CreateLogoutCmd(container di.Container) *cobra.Command {
	var opts Options
	var c *CommandContext

	l := container.Logger().With("command", "identity-logout")
	
	// Create the handler using the generated factory
	var handler Handler = NewCommand(
		container.Identity(),
		container.Token(),
		container.Profile(),
		container.Logger(),
		l,
		container.Resolver(),
	)

	cmd := &cobra.Command{
		Use:   "logout [flags]",
		Short: "Sign out from OneDrive",
		Long:  `Sign out from OneDrive for the active profile by clearing the cached authentication tokens.`,
		PreRunE: func(cmd *cobra.Command, args []string) error {
			opts.Stdout = cmd.OutOrStdout()
			opts.Stderr = cmd.ErrOrStderr()

			c = &CommandContext{
				Ctx:     cmd.Context(),
				Options: opts,
			}

			if err := handler.Validate(c); err != nil {
				return err
			}

			return handler.Resolve(c)
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := handler.Execute(c); err != nil {
				return err
			}
			return handler.Finalize(c)
		},
	}
	cmd.Flags().StringVar(&opts.Id, "id", "", "The specific account to logout (optional)")
	cmd.Flags().BoolVarP(&opts.Force, "force", "f", false, "Clear all cached credentials for the profile")

	return cmd
}
