// Code generated by spec-gen. DO NOT EDIT.
package logout

import (
	"io"
)

// Options encapsulates all user-provided arguments and flags for the command.
type Options struct {
	Id    string // The specific account to logout (optional)
	Force bool   // Clear all cached credentials for the profile

	// Stdout receives standard output messages.
	Stdout io.Writer
	// Stderr receives error and diagnostic messages.
	Stderr io.Writer
}
