// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: backend.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemType int32

const (
	ItemType_ITEM_TYPE_UNKNOWN ItemType = 0
	ItemType_ITEM_TYPE_FILE    ItemType = 1
	ItemType_ITEM_TYPE_FOLDER  ItemType = 2
)

// Enum value maps for ItemType.
var (
	ItemType_name = map[int32]string{
		0: "ITEM_TYPE_UNKNOWN",
		1: "ITEM_TYPE_FILE",
		2: "ITEM_TYPE_FOLDER",
	}
	ItemType_value = map[string]int32{
		"ITEM_TYPE_UNKNOWN": 0,
		"ITEM_TYPE_FILE":    1,
		"ITEM_TYPE_FOLDER":  2,
	}
)

func (x ItemType) Enum() *ItemType {
	p := new(ItemType)
	*p = x
	return p
}

func (x ItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_backend_proto_enumTypes[0].Descriptor()
}

func (ItemType) Type() protoreflect.EnumType {
	return &file_backend_proto_enumTypes[0]
}

func (x ItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemType.Descriptor instead.
func (ItemType) EnumDescriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{0}
}

type Drive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Owner         string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,5,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Drive) Reset() {
	*x = Drive{}
	mi := &file_backend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Drive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drive) ProtoMessage() {}

func (x *Drive) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drive.ProtoReflect.Descriptor instead.
func (*Drive) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{0}
}

func (x *Drive) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Drive) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Drive) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Drive) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Drive) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type ListDrivesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDrivesRequest) Reset() {
	*x = ListDrivesRequest{}
	mi := &file_backend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDrivesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDrivesRequest) ProtoMessage() {}

func (x *ListDrivesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDrivesRequest.ProtoReflect.Descriptor instead.
func (*ListDrivesRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{1}
}

func (x *ListDrivesRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type ListDrivesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drives        []*Drive               `protobuf:"bytes,1,rep,name=drives,proto3" json:"drives,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDrivesResponse) Reset() {
	*x = ListDrivesResponse{}
	mi := &file_backend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDrivesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDrivesResponse) ProtoMessage() {}

func (x *ListDrivesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDrivesResponse.ProtoReflect.Descriptor instead.
func (*ListDrivesResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{2}
}

func (x *ListDrivesResponse) GetDrives() []*Drive {
	if x != nil {
		return x.Drives
	}
	return nil
}

type GetPersonalDriveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPersonalDriveRequest) Reset() {
	*x = GetPersonalDriveRequest{}
	mi := &file_backend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPersonalDriveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonalDriveRequest) ProtoMessage() {}

func (x *GetPersonalDriveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonalDriveRequest.ProtoReflect.Descriptor instead.
func (*GetPersonalDriveRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{3}
}

func (x *GetPersonalDriveRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type GetPersonalDriveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drive         *Drive                 `protobuf:"bytes,1,opt,name=drive,proto3" json:"drive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPersonalDriveResponse) Reset() {
	*x = GetPersonalDriveResponse{}
	mi := &file_backend_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPersonalDriveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonalDriveResponse) ProtoMessage() {}

func (x *GetPersonalDriveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonalDriveResponse.ProtoReflect.Descriptor instead.
func (*GetPersonalDriveResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{4}
}

func (x *GetPersonalDriveResponse) GetDrive() *Drive {
	if x != nil {
		return x.Drive
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Type          ItemType               `protobuf:"varint,4,opt,name=type,proto3,enum=v1.ItemType" json:"type,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	ModifiedAt    int64                  `protobuf:"varint,6,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"` // Unix timestamp
	Etag          string                 `protobuf:"bytes,7,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_backend_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{5}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Item) GetType() ItemType {
	if x != nil {
		return x.Type
	}
	return ItemType_ITEM_TYPE_UNKNOWN
}

func (x *Item) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Item) GetModifiedAt() int64 {
	if x != nil {
		return x.ModifiedAt
	}
	return 0
}

func (x *Item) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

type Capabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CanMove       bool                   `protobuf:"varint,1,opt,name=can_move,json=canMove,proto3" json:"can_move,omitempty"`
	CanCopy       bool                   `protobuf:"varint,2,opt,name=can_copy,json=canCopy,proto3" json:"can_copy,omitempty"`
	CanRecursive  bool                   `protobuf:"varint,3,opt,name=can_recursive,json=canRecursive,proto3" json:"can_recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_backend_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{6}
}

func (x *Capabilities) GetCanMove() bool {
	if x != nil {
		return x.CanMove
	}
	return false
}

func (x *Capabilities) GetCanCopy() bool {
	if x != nil {
		return x.CanCopy
	}
	return false
}

func (x *Capabilities) GetCanRecursive() bool {
	if x != nil {
		return x.CanRecursive
	}
	return false
}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	DriveId       string                 `protobuf:"bytes,2,opt,name=drive_id,json=driveId,proto3" json:"drive_id,omitempty"`
	AccessToken   string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_backend_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{7}
}

func (x *StatRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StatRequest) GetDriveId() string {
	if x != nil {
		return x.DriveId
	}
	return ""
}

func (x *StatRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_backend_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{8}
}

func (x *StatResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	DriveId       string                 `protobuf:"bytes,2,opt,name=drive_id,json=driveId,proto3" json:"drive_id,omitempty"`
	AccessToken   string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_backend_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{9}
}

func (x *ListRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListRequest) GetDriveId() string {
	if x != nil {
		return x.DriveId
	}
	return ""
}

func (x *ListRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_backend_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{10}
}

func (x *ListResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type OpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	DriveId       string                 `protobuf:"bytes,2,opt,name=drive_id,json=driveId,proto3" json:"drive_id,omitempty"`
	AccessToken   string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_backend_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{11}
}

func (x *OpenRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *OpenRequest) GetDriveId() string {
	if x != nil {
		return x.DriveId
	}
	return ""
}

func (x *OpenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type OpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenResponse) Reset() {
	*x = OpenResponse{}
	mi := &file_backend_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenResponse) ProtoMessage() {}

func (x *OpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenResponse.ProtoReflect.Descriptor instead.
func (*OpenResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{12}
}

func (x *OpenResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*CreateRequest_Path
	//	*CreateRequest_Data
	//	*CreateRequest_DriveId
	//	*CreateRequest_AccessToken
	Request       isCreateRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_backend_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{13}
}

func (x *CreateRequest) GetRequest() isCreateRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *CreateRequest) GetPath() string {
	if x != nil {
		if x, ok := x.Request.(*CreateRequest_Path); ok {
			return x.Path
		}
	}
	return ""
}

func (x *CreateRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Request.(*CreateRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *CreateRequest) GetDriveId() string {
	if x != nil {
		if x, ok := x.Request.(*CreateRequest_DriveId); ok {
			return x.DriveId
		}
	}
	return ""
}

func (x *CreateRequest) GetAccessToken() string {
	if x != nil {
		if x, ok := x.Request.(*CreateRequest_AccessToken); ok {
			return x.AccessToken
		}
	}
	return ""
}

type isCreateRequest_Request interface {
	isCreateRequest_Request()
}

type CreateRequest_Path struct {
	Path string `protobuf:"bytes,1,opt,name=path,proto3,oneof"`
}

type CreateRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type CreateRequest_DriveId struct {
	DriveId string `protobuf:"bytes,3,opt,name=drive_id,json=driveId,proto3,oneof"`
}

type CreateRequest_AccessToken struct {
	AccessToken string `protobuf:"bytes,4,opt,name=access_token,json=accessToken,proto3,oneof"`
}

func (*CreateRequest_Path) isCreateRequest_Request() {}

func (*CreateRequest_Data) isCreateRequest_Request() {}

func (*CreateRequest_DriveId) isCreateRequest_Request() {}

func (*CreateRequest_AccessToken) isCreateRequest_Request() {}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_backend_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{14}
}

func (x *CreateResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type MkdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	DriveId       string                 `protobuf:"bytes,2,opt,name=drive_id,json=driveId,proto3" json:"drive_id,omitempty"`
	AccessToken   string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirRequest) Reset() {
	*x = MkdirRequest{}
	mi := &file_backend_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirRequest) ProtoMessage() {}

func (x *MkdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirRequest.ProtoReflect.Descriptor instead.
func (*MkdirRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{15}
}

func (x *MkdirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MkdirRequest) GetDriveId() string {
	if x != nil {
		return x.DriveId
	}
	return ""
}

func (x *MkdirRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type MkdirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirResponse) Reset() {
	*x = MkdirResponse{}
	mi := &file_backend_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirResponse) ProtoMessage() {}

func (x *MkdirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirResponse.ProtoReflect.Descriptor instead.
func (*MkdirResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{16}
}

type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	DriveId       string                 `protobuf:"bytes,2,opt,name=drive_id,json=driveId,proto3" json:"drive_id,omitempty"`
	AccessToken   string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_backend_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{17}
}

func (x *RemoveRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RemoveRequest) GetDriveId() string {
	if x != nil {
		return x.DriveId
	}
	return ""
}

func (x *RemoveRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type RemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveResponse) Reset() {
	*x = RemoveResponse{}
	mi := &file_backend_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResponse) ProtoMessage() {}

func (x *RemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResponse.ProtoReflect.Descriptor instead.
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{18}
}

type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_backend_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{19}
}

type CapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  *Capabilities          `protobuf:"bytes,1,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_backend_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{20}
}

func (x *CapabilitiesResponse) GetCapabilities() *Capabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type MoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           string                 `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst           string                 `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
	DriveId       string                 `protobuf:"bytes,3,opt,name=drive_id,json=driveId,proto3" json:"drive_id,omitempty"`
	AccessToken   string                 `protobuf:"bytes,4,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	mi := &file_backend_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{21}
}

func (x *MoveRequest) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *MoveRequest) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *MoveRequest) GetDriveId() string {
	if x != nil {
		return x.DriveId
	}
	return ""
}

func (x *MoveRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type MoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveResponse) Reset() {
	*x = MoveResponse{}
	mi := &file_backend_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResponse) ProtoMessage() {}

func (x *MoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResponse.ProtoReflect.Descriptor instead.
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{22}
}

type CopyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           string                 `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst           string                 `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
	DriveId       string                 `protobuf:"bytes,3,opt,name=drive_id,json=driveId,proto3" json:"drive_id,omitempty"`
	AccessToken   string                 `protobuf:"bytes,4,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyRequest) Reset() {
	*x = CopyRequest{}
	mi := &file_backend_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyRequest) ProtoMessage() {}

func (x *CopyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyRequest.ProtoReflect.Descriptor instead.
func (*CopyRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{23}
}

func (x *CopyRequest) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *CopyRequest) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *CopyRequest) GetDriveId() string {
	if x != nil {
		return x.DriveId
	}
	return ""
}

func (x *CopyRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type CopyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyResponse) Reset() {
	*x = CopyResponse{}
	mi := &file_backend_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyResponse) ProtoMessage() {}

func (x *CopyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyResponse.ProtoReflect.Descriptor instead.
func (*CopyResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{24}
}

var File_backend_proto protoreflect.FileDescriptor

const file_backend_proto_rawDesc = "" +
	"\n" +
	"\rbackend.proto\x12\x02v1\"r\n" +
	"\x05Drive\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12\x1b\n" +
	"\tread_only\x18\x05 \x01(\bR\breadOnly\"6\n" +
	"\x11ListDrivesRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"7\n" +
	"\x12ListDrivesResponse\x12!\n" +
	"\x06drives\x18\x01 \x03(\v2\t.v1.DriveR\x06drives\"<\n" +
	"\x17GetPersonalDriveRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\";\n" +
	"\x18GetPersonalDriveResponse\x12\x1f\n" +
	"\x05drive\x18\x01 \x01(\v2\t.v1.DriveR\x05drive\"\xa9\x01\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12 \n" +
	"\x04type\x18\x04 \x01(\x0e2\f.v1.ItemTypeR\x04type\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x12\x1f\n" +
	"\vmodified_at\x18\x06 \x01(\x03R\n" +
	"modifiedAt\x12\x12\n" +
	"\x04etag\x18\a \x01(\tR\x04etag\"i\n" +
	"\fCapabilities\x12\x19\n" +
	"\bcan_move\x18\x01 \x01(\bR\acanMove\x12\x19\n" +
	"\bcan_copy\x18\x02 \x01(\bR\acanCopy\x12#\n" +
	"\rcan_recursive\x18\x03 \x01(\bR\fcanRecursive\"_\n" +
	"\vStatRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x19\n" +
	"\bdrive_id\x18\x02 \x01(\tR\adriveId\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\",\n" +
	"\fStatResponse\x12\x1c\n" +
	"\x04item\x18\x01 \x01(\v2\b.v1.ItemR\x04item\"_\n" +
	"\vListRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x19\n" +
	"\bdrive_id\x18\x02 \x01(\tR\adriveId\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\".\n" +
	"\fListResponse\x12\x1e\n" +
	"\x05items\x18\x01 \x03(\v2\b.v1.ItemR\x05items\"_\n" +
	"\vOpenRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x19\n" +
	"\bdrive_id\x18\x02 \x01(\tR\adriveId\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\"\"\n" +
	"\fOpenResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x88\x01\n" +
	"\rCreateRequest\x12\x14\n" +
	"\x04path\x18\x01 \x01(\tH\x00R\x04path\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04data\x12\x1b\n" +
	"\bdrive_id\x18\x03 \x01(\tH\x00R\adriveId\x12#\n" +
	"\faccess_token\x18\x04 \x01(\tH\x00R\vaccessTokenB\t\n" +
	"\arequest\".\n" +
	"\x0eCreateResponse\x12\x1c\n" +
	"\x04item\x18\x01 \x01(\v2\b.v1.ItemR\x04item\"`\n" +
	"\fMkdirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x19\n" +
	"\bdrive_id\x18\x02 \x01(\tR\adriveId\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\"\x0f\n" +
	"\rMkdirResponse\"a\n" +
	"\rRemoveRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x19\n" +
	"\bdrive_id\x18\x02 \x01(\tR\adriveId\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\"\x10\n" +
	"\x0eRemoveResponse\"\x15\n" +
	"\x13CapabilitiesRequest\"L\n" +
	"\x14CapabilitiesResponse\x124\n" +
	"\fcapabilities\x18\x01 \x01(\v2\x10.v1.CapabilitiesR\fcapabilities\"o\n" +
	"\vMoveRequest\x12\x10\n" +
	"\x03src\x18\x01 \x01(\tR\x03src\x12\x10\n" +
	"\x03dst\x18\x02 \x01(\tR\x03dst\x12\x19\n" +
	"\bdrive_id\x18\x03 \x01(\tR\adriveId\x12!\n" +
	"\faccess_token\x18\x04 \x01(\tR\vaccessToken\"\x0e\n" +
	"\fMoveResponse\"o\n" +
	"\vCopyRequest\x12\x10\n" +
	"\x03src\x18\x01 \x01(\tR\x03src\x12\x10\n" +
	"\x03dst\x18\x02 \x01(\tR\x03dst\x12\x19\n" +
	"\bdrive_id\x18\x03 \x01(\tR\adriveId\x12!\n" +
	"\faccess_token\x18\x04 \x01(\tR\vaccessToken\"\x0e\n" +
	"\fCopyResponse*K\n" +
	"\bItemType\x12\x15\n" +
	"\x11ITEM_TYPE_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eITEM_TYPE_FILE\x10\x01\x12\x14\n" +
	"\x10ITEM_TYPE_FOLDER\x10\x022\xca\x04\n" +
	"\x0eBackendService\x12)\n" +
	"\x04Stat\x12\x0f.v1.StatRequest\x1a\x10.v1.StatResponse\x12)\n" +
	"\x04List\x12\x0f.v1.ListRequest\x1a\x10.v1.ListResponse\x12+\n" +
	"\x04Open\x12\x0f.v1.OpenRequest\x1a\x10.v1.OpenResponse0\x01\x121\n" +
	"\x06Create\x12\x11.v1.CreateRequest\x1a\x12.v1.CreateResponse(\x01\x12,\n" +
	"\x05Mkdir\x12\x10.v1.MkdirRequest\x1a\x11.v1.MkdirResponse\x12/\n" +
	"\x06Remove\x12\x11.v1.RemoveRequest\x1a\x12.v1.RemoveResponse\x12A\n" +
	"\fCapabilities\x12\x17.v1.CapabilitiesRequest\x1a\x18.v1.CapabilitiesResponse\x12)\n" +
	"\x04Move\x12\x0f.v1.MoveRequest\x1a\x10.v1.MoveResponse\x12)\n" +
	"\x04Copy\x12\x0f.v1.CopyRequest\x1a\x10.v1.CopyResponse\x12;\n" +
	"\n" +
	"ListDrives\x12\x15.v1.ListDrivesRequest\x1a\x16.v1.ListDrivesResponse\x12M\n" +
	"\x10GetPersonalDrive\x12\x1b.v1.GetPersonalDriveRequest\x1a\x1c.v1.GetPersonalDriveResponseBKZIgithub.com/michaeldcanady/go-onedrive/internal/storage/backend/grpc/protob\x06proto3"

var (
	file_backend_proto_rawDescOnce sync.Once
	file_backend_proto_rawDescData []byte
)

func file_backend_proto_rawDescGZIP() []byte {
	file_backend_proto_rawDescOnce.Do(func() {
		file_backend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_proto_rawDesc), len(file_backend_proto_rawDesc)))
	})
	return file_backend_proto_rawDescData
}

var file_backend_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_backend_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_backend_proto_goTypes = []any{
	(ItemType)(0),                    // 0: v1.ItemType
	(*Drive)(nil),                    // 1: v1.Drive
	(*ListDrivesRequest)(nil),        // 2: v1.ListDrivesRequest
	(*ListDrivesResponse)(nil),       // 3: v1.ListDrivesResponse
	(*GetPersonalDriveRequest)(nil),  // 4: v1.GetPersonalDriveRequest
	(*GetPersonalDriveResponse)(nil), // 5: v1.GetPersonalDriveResponse
	(*Item)(nil),                     // 6: v1.Item
	(*Capabilities)(nil),             // 7: v1.Capabilities
	(*StatRequest)(nil),              // 8: v1.StatRequest
	(*StatResponse)(nil),             // 9: v1.StatResponse
	(*ListRequest)(nil),              // 10: v1.ListRequest
	(*ListResponse)(nil),             // 11: v1.ListResponse
	(*OpenRequest)(nil),              // 12: v1.OpenRequest
	(*OpenResponse)(nil),             // 13: v1.OpenResponse
	(*CreateRequest)(nil),            // 14: v1.CreateRequest
	(*CreateResponse)(nil),           // 15: v1.CreateResponse
	(*MkdirRequest)(nil),             // 16: v1.MkdirRequest
	(*MkdirResponse)(nil),            // 17: v1.MkdirResponse
	(*RemoveRequest)(nil),            // 18: v1.RemoveRequest
	(*RemoveResponse)(nil),           // 19: v1.RemoveResponse
	(*CapabilitiesRequest)(nil),      // 20: v1.CapabilitiesRequest
	(*CapabilitiesResponse)(nil),     // 21: v1.CapabilitiesResponse
	(*MoveRequest)(nil),              // 22: v1.MoveRequest
	(*MoveResponse)(nil),             // 23: v1.MoveResponse
	(*CopyRequest)(nil),              // 24: v1.CopyRequest
	(*CopyResponse)(nil),             // 25: v1.CopyResponse
}
var file_backend_proto_depIdxs = []int32{
	1,  // 0: v1.ListDrivesResponse.drives:type_name -> v1.Drive
	1,  // 1: v1.GetPersonalDriveResponse.drive:type_name -> v1.Drive
	0,  // 2: v1.Item.type:type_name -> v1.ItemType
	6,  // 3: v1.StatResponse.item:type_name -> v1.Item
	6,  // 4: v1.ListResponse.items:type_name -> v1.Item
	6,  // 5: v1.CreateResponse.item:type_name -> v1.Item
	7,  // 6: v1.CapabilitiesResponse.capabilities:type_name -> v1.Capabilities
	8,  // 7: v1.BackendService.Stat:input_type -> v1.StatRequest
	10, // 8: v1.BackendService.List:input_type -> v1.ListRequest
	12, // 9: v1.BackendService.Open:input_type -> v1.OpenRequest
	14, // 10: v1.BackendService.Create:input_type -> v1.CreateRequest
	16, // 11: v1.BackendService.Mkdir:input_type -> v1.MkdirRequest
	18, // 12: v1.BackendService.Remove:input_type -> v1.RemoveRequest
	20, // 13: v1.BackendService.Capabilities:input_type -> v1.CapabilitiesRequest
	22, // 14: v1.BackendService.Move:input_type -> v1.MoveRequest
	24, // 15: v1.BackendService.Copy:input_type -> v1.CopyRequest
	2,  // 16: v1.BackendService.ListDrives:input_type -> v1.ListDrivesRequest
	4,  // 17: v1.BackendService.GetPersonalDrive:input_type -> v1.GetPersonalDriveRequest
	9,  // 18: v1.BackendService.Stat:output_type -> v1.StatResponse
	11, // 19: v1.BackendService.List:output_type -> v1.ListResponse
	13, // 20: v1.BackendService.Open:output_type -> v1.OpenResponse
	15, // 21: v1.BackendService.Create:output_type -> v1.CreateResponse
	17, // 22: v1.BackendService.Mkdir:output_type -> v1.MkdirResponse
	19, // 23: v1.BackendService.Remove:output_type -> v1.RemoveResponse
	21, // 24: v1.BackendService.Capabilities:output_type -> v1.CapabilitiesResponse
	23, // 25: v1.BackendService.Move:output_type -> v1.MoveResponse
	25, // 26: v1.BackendService.Copy:output_type -> v1.CopyResponse
	3,  // 27: v1.BackendService.ListDrives:output_type -> v1.ListDrivesResponse
	5,  // 28: v1.BackendService.GetPersonalDrive:output_type -> v1.GetPersonalDriveResponse
	18, // [18:29] is the sub-list for method output_type
	7,  // [7:18] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_backend_proto_init() }
func file_backend_proto_init() {
	if File_backend_proto != nil {
		return
	}
	file_backend_proto_msgTypes[13].OneofWrappers = []any{
		(*CreateRequest_Path)(nil),
		(*CreateRequest_Data)(nil),
		(*CreateRequest_DriveId)(nil),
		(*CreateRequest_AccessToken)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_proto_rawDesc), len(file_backend_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_proto_goTypes,
		DependencyIndexes: file_backend_proto_depIdxs,
		EnumInfos:         file_backend_proto_enumTypes,
		MessageInfos:      file_backend_proto_msgTypes,
	}.Build()
	File_backend_proto = out.File
	file_backend_proto_goTypes = nil
	file_backend_proto_depIdxs = nil
}
