// Code generated by spec-gen. DO NOT EDIT.
package set

import (
	"io"
)

// Options encapsulates all user-provided arguments and flags for the command.
type Options struct {
	Key string // The configuration key to update.
	Value string // The new value for the configuration setting.

	// Stdout receives standard output messages.
	Stdout io.Writer
	// Stderr receives error and diagnostic messages.
	Stderr io.Writer
}
