// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: internal/identity/proto/identity.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Method           string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"` // "interactive", "device_code", "client_secret"
	IdentityId       string                 `protobuf:"bytes,2,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	Force            bool                   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	ProviderSpecific map[string]string      `protobuf:"bytes,4,rep,name=provider_specific,json=providerSpecific,proto3" json:"provider_specific,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_internal_identity_proto_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_identity_proto_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_internal_identity_proto_identity_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AuthenticateRequest) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *AuthenticateRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *AuthenticateRequest) GetProviderSpecific() map[string]string {
	if x != nil {
		return x.ProviderSpecific
	}
	return nil
}

type AuthenticateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *AccessToken           `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Identity      *Identity              `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_internal_identity_proto_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_identity_proto_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_internal_identity_proto_identity_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticateResponse) GetToken() *AccessToken {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *AuthenticateResponse) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type GetTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityId    string                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	Scopes        []string               `protobuf:"bytes,2,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenRequest) Reset() {
	*x = GetTokenRequest{}
	mi := &file_internal_identity_proto_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenRequest) ProtoMessage() {}

func (x *GetTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_identity_proto_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenRequest.ProtoReflect.Descriptor instead.
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return file_internal_identity_proto_identity_proto_rawDescGZIP(), []int{2}
}

func (x *GetTokenRequest) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *GetTokenRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type GetTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *AccessToken           `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenResponse) Reset() {
	*x = GetTokenResponse{}
	mi := &file_internal_identity_proto_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenResponse) ProtoMessage() {}

func (x *GetTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_identity_proto_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenResponse.ProtoReflect.Descriptor instead.
func (*GetTokenResponse) Descriptor() ([]byte, []int) {
	return file_internal_identity_proto_identity_proto_rawDescGZIP(), []int{3}
}

func (x *GetTokenResponse) GetToken() *AccessToken {
	if x != nil {
		return x.Token
	}
	return nil
}

type ListIdentitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIdentitiesRequest) Reset() {
	*x = ListIdentitiesRequest{}
	mi := &file_internal_identity_proto_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIdentitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIdentitiesRequest) ProtoMessage() {}

func (x *ListIdentitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_identity_proto_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIdentitiesRequest.ProtoReflect.Descriptor instead.
func (*ListIdentitiesRequest) Descriptor() ([]byte, []int) {
	return file_internal_identity_proto_identity_proto_rawDescGZIP(), []int{4}
}

type ListIdentitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identities    []*Identity            `protobuf:"bytes,1,rep,name=identities,proto3" json:"identities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIdentitiesResponse) Reset() {
	*x = ListIdentitiesResponse{}
	mi := &file_internal_identity_proto_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIdentitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIdentitiesResponse) ProtoMessage() {}

func (x *ListIdentitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_identity_proto_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIdentitiesResponse.ProtoReflect.Descriptor instead.
func (*ListIdentitiesResponse) Descriptor() ([]byte, []int) {
	return file_internal_identity_proto_identity_proto_rawDescGZIP(), []int{5}
}

func (x *ListIdentitiesResponse) GetIdentities() []*Identity {
	if x != nil {
		return x.Identities
	}
	return nil
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityId    string                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_internal_identity_proto_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_identity_proto_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_internal_identity_proto_identity_proto_rawDescGZIP(), []int{6}
}

func (x *LogoutRequest) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_internal_identity_proto_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_identity_proto_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_internal_identity_proto_identity_proto_rawDescGZIP(), []int{7}
}

type AccessToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Unix timestamp
	Scopes        []string               `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessToken) Reset() {
	*x = AccessToken{}
	mi := &file_internal_identity_proto_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessToken) ProtoMessage() {}

func (x *AccessToken) ProtoReflect() protoreflect.Message {
	mi := &file_internal_identity_proto_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessToken.ProtoReflect.Descriptor instead.
func (*AccessToken) Descriptor() ([]byte, []int) {
	return file_internal_identity_proto_identity_proto_rawDescGZIP(), []int{8}
}

func (x *AccessToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AccessToken) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *AccessToken) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *AccessToken) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type Identity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Provider      string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_internal_identity_proto_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_internal_identity_proto_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_internal_identity_proto_identity_proto_rawDescGZIP(), []int{9}
}

func (x *Identity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Identity) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Identity) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Identity) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Identity) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Identity) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_internal_identity_proto_identity_proto protoreflect.FileDescriptor

const file_internal_identity_proto_identity_proto_rawDesc = "" +
	"\n" +
	"&internal/identity/proto/identity.proto\x12\x0fodc.identity.v1\"\x92\x02\n" +
	"\x13AuthenticateRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x1f\n" +
	"\videntity_id\x18\x02 \x01(\tR\n" +
	"identityId\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\x12g\n" +
	"\x11provider_specific\x18\x04 \x03(\v2:.odc.identity.v1.AuthenticateRequest.ProviderSpecificEntryR\x10providerSpecific\x1aC\n" +
	"\x15ProviderSpecificEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x01\n" +
	"\x14AuthenticateResponse\x122\n" +
	"\x05token\x18\x01 \x01(\v2\x1c.odc.identity.v1.AccessTokenR\x05token\x125\n" +
	"\bidentity\x18\x02 \x01(\v2\x19.odc.identity.v1.IdentityR\bidentity\"J\n" +
	"\x0fGetTokenRequest\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\x12\x16\n" +
	"\x06scopes\x18\x02 \x03(\tR\x06scopes\"F\n" +
	"\x10GetTokenResponse\x122\n" +
	"\x05token\x18\x01 \x01(\v2\x1c.odc.identity.v1.AccessTokenR\x05token\"\x17\n" +
	"\x15ListIdentitiesRequest\"S\n" +
	"\x16ListIdentitiesResponse\x129\n" +
	"\n" +
	"identities\x18\x01 \x03(\v2\x19.odc.identity.v1.IdentityR\n" +
	"identities\"0\n" +
	"\rLogoutRequest\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\"\x10\n" +
	"\x0eLogoutResponse\"\x7f\n" +
	"\vAccessToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\x12\x16\n" +
	"\x06scopes\x18\x04 \x03(\tR\x06scopes\"\x90\x02\n" +
	"\bIdentity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tR\tavatarUrl\x12C\n" +
	"\bmetadata\x18\x06 \x03(\v2'.odc.identity.v1.Identity.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xee\x02\n" +
	"\x10IdentityProvider\x12[\n" +
	"\fAuthenticate\x12$.odc.identity.v1.AuthenticateRequest\x1a%.odc.identity.v1.AuthenticateResponse\x12O\n" +
	"\bGetToken\x12 .odc.identity.v1.GetTokenRequest\x1a!.odc.identity.v1.GetTokenResponse\x12a\n" +
	"\x0eListIdentities\x12&.odc.identity.v1.ListIdentitiesRequest\x1a'.odc.identity.v1.ListIdentitiesResponse\x12I\n" +
	"\x06Logout\x12\x1e.odc.identity.v1.LogoutRequest\x1a\x1f.odc.identity.v1.LogoutResponseBBZ@github.com/michaeldcanady/go-onedrive/internal/identity/proto;v1b\x06proto3"

var (
	file_internal_identity_proto_identity_proto_rawDescOnce sync.Once
	file_internal_identity_proto_identity_proto_rawDescData []byte
)

func file_internal_identity_proto_identity_proto_rawDescGZIP() []byte {
	file_internal_identity_proto_identity_proto_rawDescOnce.Do(func() {
		file_internal_identity_proto_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_identity_proto_identity_proto_rawDesc), len(file_internal_identity_proto_identity_proto_rawDesc)))
	})
	return file_internal_identity_proto_identity_proto_rawDescData
}

var file_internal_identity_proto_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_identity_proto_identity_proto_goTypes = []any{
	(*AuthenticateRequest)(nil),    // 0: odc.identity.v1.AuthenticateRequest
	(*AuthenticateResponse)(nil),   // 1: odc.identity.v1.AuthenticateResponse
	(*GetTokenRequest)(nil),        // 2: odc.identity.v1.GetTokenRequest
	(*GetTokenResponse)(nil),       // 3: odc.identity.v1.GetTokenResponse
	(*ListIdentitiesRequest)(nil),  // 4: odc.identity.v1.ListIdentitiesRequest
	(*ListIdentitiesResponse)(nil), // 5: odc.identity.v1.ListIdentitiesResponse
	(*LogoutRequest)(nil),          // 6: odc.identity.v1.LogoutRequest
	(*LogoutResponse)(nil),         // 7: odc.identity.v1.LogoutResponse
	(*AccessToken)(nil),            // 8: odc.identity.v1.AccessToken
	(*Identity)(nil),               // 9: odc.identity.v1.Identity
	nil,                            // 10: odc.identity.v1.AuthenticateRequest.ProviderSpecificEntry
	nil,                            // 11: odc.identity.v1.Identity.MetadataEntry
}
var file_internal_identity_proto_identity_proto_depIdxs = []int32{
	10, // 0: odc.identity.v1.AuthenticateRequest.provider_specific:type_name -> odc.identity.v1.AuthenticateRequest.ProviderSpecificEntry
	8,  // 1: odc.identity.v1.AuthenticateResponse.token:type_name -> odc.identity.v1.AccessToken
	9,  // 2: odc.identity.v1.AuthenticateResponse.identity:type_name -> odc.identity.v1.Identity
	8,  // 3: odc.identity.v1.GetTokenResponse.token:type_name -> odc.identity.v1.AccessToken
	9,  // 4: odc.identity.v1.ListIdentitiesResponse.identities:type_name -> odc.identity.v1.Identity
	11, // 5: odc.identity.v1.Identity.metadata:type_name -> odc.identity.v1.Identity.MetadataEntry
	0,  // 6: odc.identity.v1.IdentityProvider.Authenticate:input_type -> odc.identity.v1.AuthenticateRequest
	2,  // 7: odc.identity.v1.IdentityProvider.GetToken:input_type -> odc.identity.v1.GetTokenRequest
	4,  // 8: odc.identity.v1.IdentityProvider.ListIdentities:input_type -> odc.identity.v1.ListIdentitiesRequest
	6,  // 9: odc.identity.v1.IdentityProvider.Logout:input_type -> odc.identity.v1.LogoutRequest
	1,  // 10: odc.identity.v1.IdentityProvider.Authenticate:output_type -> odc.identity.v1.AuthenticateResponse
	3,  // 11: odc.identity.v1.IdentityProvider.GetToken:output_type -> odc.identity.v1.GetTokenResponse
	5,  // 12: odc.identity.v1.IdentityProvider.ListIdentities:output_type -> odc.identity.v1.ListIdentitiesResponse
	7,  // 13: odc.identity.v1.IdentityProvider.Logout:output_type -> odc.identity.v1.LogoutResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_internal_identity_proto_identity_proto_init() }
func file_internal_identity_proto_identity_proto_init() {
	if File_internal_identity_proto_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_identity_proto_identity_proto_rawDesc), len(file_internal_identity_proto_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_identity_proto_identity_proto_goTypes,
		DependencyIndexes: file_internal_identity_proto_identity_proto_depIdxs,
		MessageInfos:      file_internal_identity_proto_identity_proto_msgTypes,
	}.Build()
	File_internal_identity_proto_identity_proto = out.File
	file_internal_identity_proto_identity_proto_goTypes = nil
	file_internal_identity_proto_identity_proto_depIdxs = nil
}
