// Code generated by spec-gen. DO NOT EDIT.
package cat

import (
	"github.com/michaeldcanady/go-onedrive/internal/core/di"
	"github.com/spf13/cobra"
)

// CreateCatCmd returns a new [cobra.Command] initialized with dependencies
// and configured to execute the "cat" operation.
func CreateCatCmd(container di.Container) *cobra.Command {
	var opts Options
	var c *CommandContext

	l := container.Logger().With("command", "cat")
	
	// Create the handler using the generated factory
	var handler Handler = NewCommand(
		container.VFS(),
		container.Profile(),
		container.Logger(),
		l,
		container.Resolver(),
	)

	cmd := &cobra.Command{
		Use:   "cat <path>",
		Short: "Display file contents",
		Args:  cobra.ExactArgs(1),
		PreRunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 {
				opts.Path = args[0]
			}
			opts.Stdout = cmd.OutOrStdout()
			opts.Stderr = cmd.ErrOrStderr()

			c = &CommandContext{
				Ctx:     cmd.Context(),
				Options: opts,
			}

			if err := handler.Validate(c); err != nil {
				return err
			}

			return handler.Resolve(c)
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := handler.Execute(c); err != nil {
				return err
			}
			return handler.Finalize(c)
		},
	}

	return cmd
}
