// Code generated by spec-gen. DO NOT EDIT.
package cat

import (
	"io"
)

// Options encapsulates all user-provided arguments and flags for the command.
type Options struct {
	Path string // The filesystem path to the file to display.

	// Stdout receives standard output messages.
	Stdout io.Writer
	// Stderr receives error and diagnostic messages.
	Stderr io.Writer
}
