// Code generated by spec-gen. DO NOT EDIT.
package get

import (
	"context"
	"fmt"
	"github.com/michaeldcanady/go-onedrive/internal/core/logger"
	"github.com/michaeldcanady/go-onedrive/internal/core/resolver"
	"github.com/michaeldcanady/go-onedrive/internal/features/drive"
	"github.com/michaeldcanady/go-onedrive/internal/features/profile"
)

// CommandContext carries the execution state and parsed options for a command.
type CommandContext struct {
	Ctx     context.Context
	Options Options
}

// Handler coordinates the lifecycle of a CLI command execution.
type Handler interface {
	// Validate performs initial checks on the provided options.
	Validate(ctx *CommandContext) error

	// Resolve translates raw user input (like paths or IDs) into domain entities.
	Resolve(ctx *CommandContext) error

	// Execute performs the primary business logic of the command.
	Execute(ctx *CommandContext) error

	// Finalize handles any post-execution cleanup or output formatting.
	Finalize(ctx *CommandContext) error
}

// Command provides a base implementation for command handlers, injected with required services.
type Command struct {
	drive    drive.Service
	profile  profile.Service
	logger   logger.Service
	l        logger.Service
	resolver resolver.Service
}

// NewCommand creates a new instance of the get command handler.
func NewCommand(
	drive drive.Service,
	profile profile.Service,
	logger logger.Service,
	l logger.Service,
	r resolver.Service,
) *Command {
	return &Command{
		drive:    drive,
		profile:  profile,
		logger:   logger,
		l:        l,
		resolver: r,
	}
}

// BaseResolve handles the resolution of command arguments and flags based on the specification.
func (c *Command) BaseResolve(ctx *CommandContext) error {
	if ctx.Options.DriveRef != "" {
		resolved, err := c.resolver.ResolveDrive(ctx.Ctx, ctx.Options.DriveRef)
		if err != nil {
			return fmt.Errorf("failed to resolve drive %s: %w", ctx.Options.DriveRef, err)
		}
		ctx.Options.DriveRef = resolved.ID
	}
	if ctx.Options.Id != "" {
		resolved, err := c.resolver.ResolveIdentity(ctx.Ctx, ctx.Options.Id)
		if err != nil {
			return fmt.Errorf("failed to resolve identity %s: %w", ctx.Options.Id, err)
		}
		ctx.Options.Id = resolved.ID
	}

	return nil
}
