// Code generated by spec-gen. DO NOT EDIT.
package get

import (
	"io"
)

// Options encapsulates all user-provided arguments and flags for the command.
type Options struct {
	DriveRef string // The identifier for the drive, which can be its ID or name.
	Id       string // The specific identity (email or alias) to get the personal drive for

	// Stdout receives standard output messages.
	Stdout io.Writer
	// Stderr receives error and diagnostic messages.
	Stderr io.Writer
}
