// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: identity.proto

package identity

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdentityPlugin_Login_FullMethodName          = "/identity.IdentityPlugin/Login"
	IdentityPlugin_Refresh_FullMethodName        = "/identity.IdentityPlugin/Refresh"
	IdentityPlugin_ListIdentities_FullMethodName = "/identity.IdentityPlugin/ListIdentities"
	IdentityPlugin_Logout_FullMethodName         = "/identity.IdentityPlugin/Logout"
	IdentityPlugin_GetMetadata_FullMethodName    = "/identity.IdentityPlugin/GetMetadata"
)

// IdentityPluginClient is the client API for IdentityPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdentityPluginClient interface {
	Login(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LoginRequest, LoginResponse], error)
	Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error)
	ListIdentities(ctx context.Context, in *ListIdentitiesRequest, opts ...grpc.CallOption) (*ListIdentitiesResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	GetMetadata(ctx context.Context, in *MetadataRequest, opts ...grpc.CallOption) (*MetadataResponse, error)
}

type identityPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityPluginClient(cc grpc.ClientConnInterface) IdentityPluginClient {
	return &identityPluginClient{cc}
}

func (c *identityPluginClient) Login(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LoginRequest, LoginResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IdentityPlugin_ServiceDesc.Streams[0], IdentityPlugin_Login_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LoginRequest, LoginResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IdentityPlugin_LoginClient = grpc.BidiStreamingClient[LoginRequest, LoginResponse]

func (c *identityPluginClient) Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshResponse)
	err := c.cc.Invoke(ctx, IdentityPlugin_Refresh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityPluginClient) ListIdentities(ctx context.Context, in *ListIdentitiesRequest, opts ...grpc.CallOption) (*ListIdentitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIdentitiesResponse)
	err := c.cc.Invoke(ctx, IdentityPlugin_ListIdentities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityPluginClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, IdentityPlugin_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityPluginClient) GetMetadata(ctx context.Context, in *MetadataRequest, opts ...grpc.CallOption) (*MetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetadataResponse)
	err := c.cc.Invoke(ctx, IdentityPlugin_GetMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityPluginServer is the server API for IdentityPlugin service.
// All implementations must embed UnimplementedIdentityPluginServer
// for forward compatibility.
type IdentityPluginServer interface {
	Login(grpc.BidiStreamingServer[LoginRequest, LoginResponse]) error
	Refresh(context.Context, *RefreshRequest) (*RefreshResponse, error)
	ListIdentities(context.Context, *ListIdentitiesRequest) (*ListIdentitiesResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	GetMetadata(context.Context, *MetadataRequest) (*MetadataResponse, error)
	mustEmbedUnimplementedIdentityPluginServer()
}

// UnimplementedIdentityPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityPluginServer struct{}

func (UnimplementedIdentityPluginServer) Login(grpc.BidiStreamingServer[LoginRequest, LoginResponse]) error {
	return status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedIdentityPluginServer) Refresh(context.Context, *RefreshRequest) (*RefreshResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Refresh not implemented")
}
func (UnimplementedIdentityPluginServer) ListIdentities(context.Context, *ListIdentitiesRequest) (*ListIdentitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIdentities not implemented")
}
func (UnimplementedIdentityPluginServer) Logout(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedIdentityPluginServer) GetMetadata(context.Context, *MetadataRequest) (*MetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetadata not implemented")
}
func (UnimplementedIdentityPluginServer) mustEmbedUnimplementedIdentityPluginServer() {}
func (UnimplementedIdentityPluginServer) testEmbeddedByValue()                        {}

// UnsafeIdentityPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityPluginServer will
// result in compilation errors.
type UnsafeIdentityPluginServer interface {
	mustEmbedUnimplementedIdentityPluginServer()
}

func RegisterIdentityPluginServer(s grpc.ServiceRegistrar, srv IdentityPluginServer) {
	// If the following call panics, it indicates UnimplementedIdentityPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentityPlugin_ServiceDesc, srv)
}

func _IdentityPlugin_Login_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IdentityPluginServer).Login(&grpc.GenericServerStream[LoginRequest, LoginResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IdentityPlugin_LoginServer = grpc.BidiStreamingServer[LoginRequest, LoginResponse]

func _IdentityPlugin_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityPluginServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityPlugin_Refresh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityPluginServer).Refresh(ctx, req.(*RefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityPlugin_ListIdentities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIdentitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityPluginServer).ListIdentities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityPlugin_ListIdentities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityPluginServer).ListIdentities(ctx, req.(*ListIdentitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityPlugin_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityPluginServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityPlugin_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityPluginServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityPlugin_GetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityPluginServer).GetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityPlugin_GetMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityPluginServer).GetMetadata(ctx, req.(*MetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityPlugin_ServiceDesc is the grpc.ServiceDesc for IdentityPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "identity.IdentityPlugin",
	HandlerType: (*IdentityPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Refresh",
			Handler:    _IdentityPlugin_Refresh_Handler,
		},
		{
			MethodName: "ListIdentities",
			Handler:    _IdentityPlugin_ListIdentities_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _IdentityPlugin_Logout_Handler,
		},
		{
			MethodName: "GetMetadata",
			Handler:    _IdentityPlugin_GetMetadata_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Login",
			Handler:       _IdentityPlugin_Login_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "identity.proto",
}
