// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: identity.proto

package identity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataRequest) Reset() {
	*x = MetadataRequest{}
	mi := &file_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRequest) ProtoMessage() {}

func (x *MetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRequest.ProtoReflect.Descriptor instead.
func (*MetadataRequest) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{0}
}

type MetadataResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type               string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	SupportedProviders []string               `protobuf:"bytes,3,rep,name=supported_providers,json=supportedProviders,proto3" json:"supported_providers,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MetadataResponse) Reset() {
	*x = MetadataResponse{}
	mi := &file_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataResponse) ProtoMessage() {}

func (x *MetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataResponse.ProtoReflect.Descriptor instead.
func (*MetadataResponse) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{1}
}

func (x *MetadataResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetadataResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MetadataResponse) GetSupportedProviders() []string {
	if x != nil {
		return x.SupportedProviders
	}
	return nil
}

type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*LoginRequest_Config
	//	*LoginRequest_InteractionResponse
	Payload       isLoginRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetPayload() isLoginRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *LoginRequest) GetConfig() *Config {
	if x != nil {
		if x, ok := x.Payload.(*LoginRequest_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *LoginRequest) GetInteractionResponse() *InteractionResponse {
	if x != nil {
		if x, ok := x.Payload.(*LoginRequest_InteractionResponse); ok {
			return x.InteractionResponse
		}
	}
	return nil
}

type isLoginRequest_Payload interface {
	isLoginRequest_Payload()
}

type LoginRequest_Config struct {
	Config *Config `protobuf:"bytes,1,opt,name=config,proto3,oneof"`
}

type LoginRequest_InteractionResponse struct {
	InteractionResponse *InteractionResponse `protobuf:"bytes,2,opt,name=interaction_response,json=interactionResponse,proto3,oneof"`
}

func (*LoginRequest_Config) isLoginRequest_Payload() {}

func (*LoginRequest_InteractionResponse) isLoginRequest_Payload() {}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       map[string]string      `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{3}
}

func (x *Config) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type LoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*LoginResponse_InteractionRequest
	//	*LoginResponse_Result
	Payload       isLoginResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{4}
}

func (x *LoginResponse) GetPayload() isLoginResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *LoginResponse) GetInteractionRequest() *InteractionRequest {
	if x != nil {
		if x, ok := x.Payload.(*LoginResponse_InteractionRequest); ok {
			return x.InteractionRequest
		}
	}
	return nil
}

func (x *LoginResponse) GetResult() *LoginResult {
	if x != nil {
		if x, ok := x.Payload.(*LoginResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isLoginResponse_Payload interface {
	isLoginResponse_Payload()
}

type LoginResponse_InteractionRequest struct {
	InteractionRequest *InteractionRequest `protobuf:"bytes,1,opt,name=interaction_request,json=interactionRequest,proto3,oneof"`
}

type LoginResponse_Result struct {
	Result *LoginResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

func (*LoginResponse_InteractionRequest) isLoginResponse_Payload() {}

func (*LoginResponse_Result) isLoginResponse_Payload() {}

type LoginResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *AccessToken           `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Identity      *Identity              `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResult) Reset() {
	*x = LoginResult{}
	mi := &file_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResult) ProtoMessage() {}

func (x *LoginResult) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResult.ProtoReflect.Descriptor instead.
func (*LoginResult) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResult) GetToken() *AccessToken {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *LoginResult) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type InteractionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Action:
	//
	//	*InteractionRequest_OpenUrl
	//	*InteractionRequest_DisplayMessage
	Action        isInteractionRequest_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractionRequest) Reset() {
	*x = InteractionRequest{}
	mi := &file_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractionRequest) ProtoMessage() {}

func (x *InteractionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractionRequest.ProtoReflect.Descriptor instead.
func (*InteractionRequest) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{6}
}

func (x *InteractionRequest) GetAction() isInteractionRequest_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *InteractionRequest) GetOpenUrl() *OpenUrlRequest {
	if x != nil {
		if x, ok := x.Action.(*InteractionRequest_OpenUrl); ok {
			return x.OpenUrl
		}
	}
	return nil
}

func (x *InteractionRequest) GetDisplayMessage() *DisplayMessageRequest {
	if x != nil {
		if x, ok := x.Action.(*InteractionRequest_DisplayMessage); ok {
			return x.DisplayMessage
		}
	}
	return nil
}

type isInteractionRequest_Action interface {
	isInteractionRequest_Action()
}

type InteractionRequest_OpenUrl struct {
	OpenUrl *OpenUrlRequest `protobuf:"bytes,1,opt,name=open_url,json=openUrl,proto3,oneof"`
}

type InteractionRequest_DisplayMessage struct {
	DisplayMessage *DisplayMessageRequest `protobuf:"bytes,2,opt,name=display_message,json=displayMessage,proto3,oneof"`
}

func (*InteractionRequest_OpenUrl) isInteractionRequest_Action() {}

func (*InteractionRequest_DisplayMessage) isInteractionRequest_Action() {}

type OpenUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenUrlRequest) Reset() {
	*x = OpenUrlRequest{}
	mi := &file_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenUrlRequest) ProtoMessage() {}

func (x *OpenUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenUrlRequest.ProtoReflect.Descriptor instead.
func (*OpenUrlRequest) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{7}
}

func (x *OpenUrlRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type DisplayMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisplayMessageRequest) Reset() {
	*x = DisplayMessageRequest{}
	mi := &file_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisplayMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayMessageRequest) ProtoMessage() {}

func (x *DisplayMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplayMessageRequest.ProtoReflect.Descriptor instead.
func (*DisplayMessageRequest) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{8}
}

func (x *DisplayMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InteractionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractionResponse) Reset() {
	*x = InteractionResponse{}
	mi := &file_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractionResponse) ProtoMessage() {}

func (x *InteractionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractionResponse.ProtoReflect.Descriptor instead.
func (*InteractionResponse) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{9}
}

func (x *InteractionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Options       map[string]string      `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_identity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{10}
}

func (x *RefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type RefreshResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *AccessToken           `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshResponse) Reset() {
	*x = RefreshResponse{}
	mi := &file_identity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResponse) ProtoMessage() {}

func (x *RefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResponse.ProtoReflect.Descriptor instead.
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{11}
}

func (x *RefreshResponse) GetToken() *AccessToken {
	if x != nil {
		return x.Token
	}
	return nil
}

type ListIdentitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       map[string]string      `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIdentitiesRequest) Reset() {
	*x = ListIdentitiesRequest{}
	mi := &file_identity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIdentitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIdentitiesRequest) ProtoMessage() {}

func (x *ListIdentitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIdentitiesRequest.ProtoReflect.Descriptor instead.
func (*ListIdentitiesRequest) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{12}
}

func (x *ListIdentitiesRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type ListIdentitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identities    []*Identity            `protobuf:"bytes,1,rep,name=identities,proto3" json:"identities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIdentitiesResponse) Reset() {
	*x = ListIdentitiesResponse{}
	mi := &file_identity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIdentitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIdentitiesResponse) ProtoMessage() {}

func (x *ListIdentitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIdentitiesResponse.ProtoReflect.Descriptor instead.
func (*ListIdentitiesResponse) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{13}
}

func (x *ListIdentitiesResponse) GetIdentities() []*Identity {
	if x != nil {
		return x.Identities
	}
	return nil
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityId    string                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	Options       map[string]string      `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_identity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{14}
}

func (x *LogoutRequest) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *LogoutRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_identity_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{15}
}

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AccessToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Scopes        []string               `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessToken) Reset() {
	*x = AccessToken{}
	mi := &file_identity_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessToken) ProtoMessage() {}

func (x *AccessToken) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessToken.ProtoReflect.Descriptor instead.
func (*AccessToken) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{16}
}

func (x *AccessToken) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AccessToken) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *AccessToken) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *AccessToken) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type Identity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Provider      string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_identity_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{17}
}

func (x *Identity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Identity) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Identity) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Identity) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Identity) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_identity_proto protoreflect.FileDescriptor

const file_identity_proto_rawDesc = "" +
	"\n" +
	"\x0eidentity.proto\x12\bidentity\"\x11\n" +
	"\x0fMetadataRequest\"k\n" +
	"\x10MetadataResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12/\n" +
	"\x13supported_providers\x18\x03 \x03(\tR\x12supportedProviders\"\x99\x01\n" +
	"\fLoginRequest\x12*\n" +
	"\x06config\x18\x01 \x01(\v2\x10.identity.ConfigH\x00R\x06config\x12R\n" +
	"\x14interaction_response\x18\x02 \x01(\v2\x1d.identity.InteractionResponseH\x00R\x13interactionResponseB\t\n" +
	"\apayload\"}\n" +
	"\x06Config\x127\n" +
	"\aoptions\x18\x01 \x03(\v2\x1d.identity.Config.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9c\x01\n" +
	"\rLoginResponse\x12O\n" +
	"\x13interaction_request\x18\x01 \x01(\v2\x1c.identity.InteractionRequestH\x00R\x12interactionRequest\x12/\n" +
	"\x06result\x18\x02 \x01(\v2\x15.identity.LoginResultH\x00R\x06resultB\t\n" +
	"\apayload\"j\n" +
	"\vLoginResult\x12+\n" +
	"\x05token\x18\x01 \x01(\v2\x15.identity.AccessTokenR\x05token\x12.\n" +
	"\bidentity\x18\x02 \x01(\v2\x12.identity.IdentityR\bidentity\"\xa1\x01\n" +
	"\x12InteractionRequest\x125\n" +
	"\bopen_url\x18\x01 \x01(\v2\x18.identity.OpenUrlRequestH\x00R\aopenUrl\x12J\n" +
	"\x0fdisplay_message\x18\x02 \x01(\v2\x1f.identity.DisplayMessageRequestH\x00R\x0edisplayMessageB\b\n" +
	"\x06action\"\"\n" +
	"\x0eOpenUrlRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"1\n" +
	"\x15DisplayMessageRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"+\n" +
	"\x13InteractionResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\xb2\x01\n" +
	"\x0eRefreshRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\x12?\n" +
	"\aoptions\x18\x02 \x03(\v2%.identity.RefreshRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\x0fRefreshResponse\x12+\n" +
	"\x05token\x18\x01 \x01(\v2\x15.identity.AccessTokenR\x05token\"\x9b\x01\n" +
	"\x15ListIdentitiesRequest\x12F\n" +
	"\aoptions\x18\x01 \x03(\v2,.identity.ListIdentitiesRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"L\n" +
	"\x16ListIdentitiesResponse\x122\n" +
	"\n" +
	"identities\x18\x01 \x03(\v2\x12.identity.IdentityR\n" +
	"identities\"\xac\x01\n" +
	"\rLogoutRequest\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\x12>\n" +
	"\aoptions\x18\x02 \x03(\v2$.identity.LogoutRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8c\x01\n" +
	"\vAccessToken\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\x12\x16\n" +
	"\x06scopes\x18\x04 \x03(\tR\x06scopes\"\xea\x01\n" +
	"\bIdentity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12<\n" +
	"\bmetadata\x18\x05 \x03(\v2 .identity.Identity.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xe6\x02\n" +
	"\x0eIdentityPlugin\x12<\n" +
	"\x05Login\x12\x16.identity.LoginRequest\x1a\x17.identity.LoginResponse(\x010\x01\x12>\n" +
	"\aRefresh\x12\x18.identity.RefreshRequest\x1a\x19.identity.RefreshResponse\x12S\n" +
	"\x0eListIdentities\x12\x1f.identity.ListIdentitiesRequest\x1a .identity.ListIdentitiesResponse\x12;\n" +
	"\x06Logout\x12\x17.identity.LogoutRequest\x1a\x18.identity.LogoutResponse\x12D\n" +
	"\vGetMetadata\x12\x19.identity.MetadataRequest\x1a\x1a.identity.MetadataResponseBPZNgithub.com/michaeldcanady/go-onedrive/internal/features/plugins/proto/identityb\x06proto3"

var (
	file_identity_proto_rawDescOnce sync.Once
	file_identity_proto_rawDescData []byte
)

func file_identity_proto_rawDescGZIP() []byte {
	file_identity_proto_rawDescOnce.Do(func() {
		file_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_proto_rawDesc), len(file_identity_proto_rawDesc)))
	})
	return file_identity_proto_rawDescData
}

var file_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_identity_proto_goTypes = []any{
	(*MetadataRequest)(nil),        // 0: identity.MetadataRequest
	(*MetadataResponse)(nil),       // 1: identity.MetadataResponse
	(*LoginRequest)(nil),           // 2: identity.LoginRequest
	(*Config)(nil),                 // 3: identity.Config
	(*LoginResponse)(nil),          // 4: identity.LoginResponse
	(*LoginResult)(nil),            // 5: identity.LoginResult
	(*InteractionRequest)(nil),     // 6: identity.InteractionRequest
	(*OpenUrlRequest)(nil),         // 7: identity.OpenUrlRequest
	(*DisplayMessageRequest)(nil),  // 8: identity.DisplayMessageRequest
	(*InteractionResponse)(nil),    // 9: identity.InteractionResponse
	(*RefreshRequest)(nil),         // 10: identity.RefreshRequest
	(*RefreshResponse)(nil),        // 11: identity.RefreshResponse
	(*ListIdentitiesRequest)(nil),  // 12: identity.ListIdentitiesRequest
	(*ListIdentitiesResponse)(nil), // 13: identity.ListIdentitiesResponse
	(*LogoutRequest)(nil),          // 14: identity.LogoutRequest
	(*LogoutResponse)(nil),         // 15: identity.LogoutResponse
	(*AccessToken)(nil),            // 16: identity.AccessToken
	(*Identity)(nil),               // 17: identity.Identity
	nil,                            // 18: identity.Config.OptionsEntry
	nil,                            // 19: identity.RefreshRequest.OptionsEntry
	nil,                            // 20: identity.ListIdentitiesRequest.OptionsEntry
	nil,                            // 21: identity.LogoutRequest.OptionsEntry
	nil,                            // 22: identity.Identity.MetadataEntry
}
var file_identity_proto_depIdxs = []int32{
	3,  // 0: identity.LoginRequest.config:type_name -> identity.Config
	9,  // 1: identity.LoginRequest.interaction_response:type_name -> identity.InteractionResponse
	18, // 2: identity.Config.options:type_name -> identity.Config.OptionsEntry
	6,  // 3: identity.LoginResponse.interaction_request:type_name -> identity.InteractionRequest
	5,  // 4: identity.LoginResponse.result:type_name -> identity.LoginResult
	16, // 5: identity.LoginResult.token:type_name -> identity.AccessToken
	17, // 6: identity.LoginResult.identity:type_name -> identity.Identity
	7,  // 7: identity.InteractionRequest.open_url:type_name -> identity.OpenUrlRequest
	8,  // 8: identity.InteractionRequest.display_message:type_name -> identity.DisplayMessageRequest
	19, // 9: identity.RefreshRequest.options:type_name -> identity.RefreshRequest.OptionsEntry
	16, // 10: identity.RefreshResponse.token:type_name -> identity.AccessToken
	20, // 11: identity.ListIdentitiesRequest.options:type_name -> identity.ListIdentitiesRequest.OptionsEntry
	17, // 12: identity.ListIdentitiesResponse.identities:type_name -> identity.Identity
	21, // 13: identity.LogoutRequest.options:type_name -> identity.LogoutRequest.OptionsEntry
	22, // 14: identity.Identity.metadata:type_name -> identity.Identity.MetadataEntry
	2,  // 15: identity.IdentityPlugin.Login:input_type -> identity.LoginRequest
	10, // 16: identity.IdentityPlugin.Refresh:input_type -> identity.RefreshRequest
	12, // 17: identity.IdentityPlugin.ListIdentities:input_type -> identity.ListIdentitiesRequest
	14, // 18: identity.IdentityPlugin.Logout:input_type -> identity.LogoutRequest
	0,  // 19: identity.IdentityPlugin.GetMetadata:input_type -> identity.MetadataRequest
	4,  // 20: identity.IdentityPlugin.Login:output_type -> identity.LoginResponse
	11, // 21: identity.IdentityPlugin.Refresh:output_type -> identity.RefreshResponse
	13, // 22: identity.IdentityPlugin.ListIdentities:output_type -> identity.ListIdentitiesResponse
	15, // 23: identity.IdentityPlugin.Logout:output_type -> identity.LogoutResponse
	1,  // 24: identity.IdentityPlugin.GetMetadata:output_type -> identity.MetadataResponse
	20, // [20:25] is the sub-list for method output_type
	15, // [15:20] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_identity_proto_init() }
func file_identity_proto_init() {
	if File_identity_proto != nil {
		return
	}
	file_identity_proto_msgTypes[2].OneofWrappers = []any{
		(*LoginRequest_Config)(nil),
		(*LoginRequest_InteractionResponse)(nil),
	}
	file_identity_proto_msgTypes[4].OneofWrappers = []any{
		(*LoginResponse_InteractionRequest)(nil),
		(*LoginResponse_Result)(nil),
	}
	file_identity_proto_msgTypes[6].OneofWrappers = []any{
		(*InteractionRequest_OpenUrl)(nil),
		(*InteractionRequest_DisplayMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_proto_rawDesc), len(file_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_identity_proto_goTypes,
		DependencyIndexes: file_identity_proto_depIdxs,
		MessageInfos:      file_identity_proto_msgTypes,
	}.Build()
	File_identity_proto = out.File
	file_identity_proto_goTypes = nil
	file_identity_proto_depIdxs = nil
}
