// Code generated by spec-gen. DO NOT EDIT.
package ls

import (
	"github.com/michaeldcanady/go-onedrive/internal/core/di"
	"github.com/spf13/cobra"
)

// CreateLsCmd returns a new [cobra.Command] initialized with dependencies
// and configured to execute the "ls" operation.
func CreateLsCmd(container di.Container) *cobra.Command {
	var opts Options
	var c *CommandContext

	l := container.Logger().With("command", "ls")

	// Create the handler using the generated factory
	var handler Handler = NewCommand(
		container.VFS(),
		container.Profile(),
		container.Formatter(),
		container.Logger(),
		l,
		container.Resolver(),
	)

	cmd := &cobra.Command{
		Use:   "ls [path] [flags]",
		Short: "List items in a directory",
		Long:  `List the items in a specified directory in OneDrive or the local filesystem.`,
		Args:  cobra.MaximumNArgs(1),
		PreRunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 {
				opts.Path = args[0]
			}
			opts.Stdout = cmd.OutOrStdout()
			opts.Stderr = cmd.ErrOrStderr()

			c = &CommandContext{
				Ctx:     cmd.Context(),
				Options: opts,
			}

			if err := handler.Validate(c); err != nil {
				return err
			}

			return handler.Resolve(c)
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := handler.Execute(c); err != nil {
				return err
			}
			return handler.Finalize(c)
		},
	}
	cmd.Flags().StringVarP(&opts.Format, "format", "o", "short", "Output format (short, long, json, yaml, tree, table)")
	cmd.Flags().BoolVarP(&opts.Recursive, "recursive", "r", false, "List items recursively")
	cmd.Flags().BoolVarP(&opts.All, "all", "a", false, "Show hidden items")
	cmd.Flags().StringSliceVar(&opts.Sort, "sort", []string{"name"}, "Sort items by field (name, size, modified)")
	cmd.Flags().BoolVar(&opts.Desc, "desc", false, "Sort in descending order")

	return cmd
}
