// Code generated by spec-gen. DO NOT EDIT.
package current

import (
	"io"
)

// Options encapsulates all user-provided arguments and flags for the command.
type Options struct {

	// Stdout receives standard output messages.
	Stdout io.Writer
	// Stderr receives error and diagnostic messages.
	Stderr io.Writer
}
