name: 'Setup ODC Environment'
description: 'Setup Go with cache and install Just'
inputs:
  go-version:
    description: 'Go version to use'
    required: true
    default: '1.25.x'
  just:
    description: 'Whether to setup Just'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ inputs.go-version }}
        cache: true

    - name: Setup Just
      if: ${{ inputs.just == 'true' }}
      uses: extractions/setup-just@v2
