// Code generated by spec-gen. DO NOT EDIT.
package upload

import (
	"io"
)

// Options encapsulates all user-provided arguments and flags for the command.
type Options struct {
	Source      string // The local path to the file or directory.
	Destination string // The remote path on OneDrive where the item should be uploaded.
	Recursive   bool   // Upload directories recursively

	// Stdout receives standard output messages.
	Stdout io.Writer
	// Stderr receives error and diagnostic messages.
	Stderr io.Writer
}
