// Code generated by spec-gen. DO NOT EDIT.
package add

import (
	"github.com/michaeldcanady/go-onedrive/internal/core/di"
	"github.com/spf13/cobra"
)

// CreateAddCmd returns a new [cobra.Command] initialized with dependencies
// and configured to execute the "add" operation.
func CreateAddCmd(container di.Container) *cobra.Command {
	var opts Options
	var c *CommandContext

	l := container.Logger().With("command", "mount-add")
	
	// Create the handler using the generated factory
	var handler Handler = NewCommand(
		container.Mounts(),
		container.Profile(),
		container.Logger(),
		l,
		container.Resolver(),
	)

	cmd := &cobra.Command{
		Use:   "add <path> <type> <identity-id> [flags]",
		Short: "Add a mount point",
		Args:  cobra.ExactArgs(3),
		PreRunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 {
				opts.Path = args[0]
			}
			if len(args) > 1 {
				opts.Type = args[1]
			}
			if len(args) > 2 {
				opts.IdentityId = args[2]
			}
			opts.Stdout = cmd.OutOrStdout()
			opts.Stderr = cmd.ErrOrStderr()

			c = &CommandContext{
				Ctx:     cmd.Context(),
				Options: opts,
			}

			if err := handler.Validate(c); err != nil {
				return err
			}

			return handler.Resolve(c)
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := handler.Execute(c); err != nil {
				return err
			}
			return handler.Finalize(c)
		},
	}
	cmd.Flags().StringVar(&opts.IdentityProvider, "identity-provider", "azure", "The identity provider to use (e.g., azure, google)")
	cmd.Flags().StringSliceVar(&opts.Option, "option", []string{ }, "Provider-specific options in key=value format (repeatable)")

	return cmd
}
