// Code generated by spec-gen. DO NOT EDIT.
package get

import (
	"github.com/michaeldcanady/go-onedrive/internal/core/di"
	"github.com/spf13/cobra"
)

// CreateGetCmd returns a new [cobra.Command] initialized with dependencies
// and configured to execute the "get" operation.
func CreateGetCmd(container di.Container) *cobra.Command {
	var opts Options
	var c *CommandContext

	l := container.Logger().With("command", "config-get")

	// Create the handler using the generated factory
	var handler Handler = NewCommand(
		container.Config(),
		container.Formatter(),
		container.Logger(),
		l,
		container.Resolver(),
	)

	cmd := &cobra.Command{
		Use:   "get [key] [flags]",
		Short: "Get configuration",
		Args:  cobra.ExactArgs(1),
		PreRunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 {
				opts.Key = args[0]
			}
			opts.Stdout = cmd.OutOrStdout()
			opts.Stderr = cmd.ErrOrStderr()

			c = &CommandContext{
				Ctx:     cmd.Context(),
				Options: opts,
			}

			if err := handler.Validate(c); err != nil {
				return err
			}

			return handler.Resolve(c)
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := handler.Execute(c); err != nil {
				return err
			}
			return handler.Finalize(c)
		},
	}
	cmd.Flags().StringVarP(&opts.Format, "format", "o", "value", "Output format (value, json, yaml)")

	return cmd
}
