// Code generated by spec-gen. DO NOT EDIT.
package get

import (
	"context"
	"github.com/michaeldcanady/go-onedrive/internal/core/logger"
	"github.com/michaeldcanady/go-onedrive/internal/core/resolver"
	"github.com/michaeldcanady/go-onedrive/internal/features/config"
	"github.com/michaeldcanady/go-onedrive/pkg/format"
)

// CommandContext carries the execution state and parsed options for a command.
type CommandContext struct {
	Ctx     context.Context
	Options Options
}

// Handler coordinates the lifecycle of a CLI command execution.
type Handler interface {
	// Validate performs initial checks on the provided options.
	Validate(ctx *CommandContext) error

	// Resolve translates raw user input (like paths or IDs) into domain entities.
	Resolve(ctx *CommandContext) error

	// Execute performs the primary business logic of the command.
	Execute(ctx *CommandContext) error

	// Finalize handles any post-execution cleanup or output formatting.
	Finalize(ctx *CommandContext) error
}

// Command provides a base implementation for command handlers, injected with required services.
type Command struct {
	config    config.Service
	formatter format.Factory
	logger    logger.Service
	l         logger.Service
	resolver  resolver.Service
}

// NewCommand creates a new instance of the get command handler.
func NewCommand(
	config config.Service,
	formatter format.Factory,
	logger logger.Service,
	l logger.Service,
	r resolver.Service,
) *Command {
	return &Command{
		config:    config,
		formatter: formatter,
		logger:    logger,
		l:         l,
		resolver:  r,
	}
}

// BaseResolve handles the resolution of command arguments and flags based on the specification.
func (c *Command) BaseResolve(ctx *CommandContext) error {

	return nil
}
