// Code generated by spec-gen. DO NOT EDIT.
package get

import (
	"io"
)

// Options encapsulates all user-provided arguments and flags for the command.
type Options struct {
	Key    string // The configuration key to retrieve (e.g., auth.provider, logging.level).
	Format string // Output format (value, json, yaml)

	// Stdout receives standard output messages.
	Stdout io.Writer
	// Stderr receives error and diagnostic messages.
	Stderr io.Writer
}
