// Code generated by spec-gen. DO NOT EDIT.
package delete

import (
	"io"
)

// Options encapsulates all user-provided arguments and flags for the command.
type Options struct {
	Name string // The name of the profile to delete.

	// Stdout receives standard output messages.
	Stdout io.Writer
	// Stderr receives error and diagnostic messages.
	Stderr io.Writer
}
