name: (Internal) Validate Docs

on:
  workflow_call:
    inputs:
      ref:
        description: 'Git ref to checkout'
        required: false
        type: string
        default: ''

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}

      - name: Vale Lint
        uses: errata-ai/vale-action@v2
        with:
          files: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lychee Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress 'docs/**/*.md' 'README.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
