name: ~ Lint Go

on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string

jobs:
  lint:
    name: Lint Go Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Setup Environment
        uses: ./.github/actions/setup-odc
        with:
          go-version: ${{ inputs.go-version }}
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          skip-cache: false
