name: ~ Performance Benchmarking

on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string

jobs:
  benchmark:
    name: Performance Benchmarking
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Setup Environment
        uses: ./.github/actions/setup-odc
        with:
          go-version: ${{ inputs.go-version }}
      - name: Run benchmarks
        run: go test -v -bench=. -benchmem -run=^$ ./... | tee benchmark_output.txt
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Go Benchmark
          tool: 'go'
          output-file-path: benchmark_output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
