name: Deploy docs

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  validate:
    uses: ./.github/workflows/_docs-validate.yaml

  deploy-docs:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Docs
        uses: ./.github/actions/setup-docs

      - name: Deploy documentation
        run: |
          mkdocs gh-deploy --force
