name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    environment: CLOUDSMITH_API_KEY
    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup-odc
        with:
          fetch-depth: 0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_GITHUB_TOKEN: ${{ secrets.HOMEBREW_GITHUB_TOKEN }}

      - name: Install Cloudsmith
        uses: cloudsmith-io/cloudsmith-cli-action@v1
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}

      - name: Upload artifacts to Cloudsmith
        shell: bash
        run: |
          for file in dist/*.deb; do
            [ -e "$file" ] || continue
            cloudsmith push deb michaeldcanady/odc/debian/nodistro "$file"
          done
          for file in dist/*.rpm; do
            [ -e "$file" ] || continue
            cloudsmith push rpm michaeldcanady/odc/rhel/any-version "$file"
          done
          for file in dist/*.apk; do
            [ -e "$file" ] || continue
            cloudsmith push alpine michaeldcanady/odc/alpine/any-version "$file"
          done
