name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    environment: CLOUDSMITH_API_KEY
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_GITHUB_TOKEN: ${{ secrets.HOMEBREW_GITHUB_TOKEN }}
      - name: Run Cloudsmith
        uses: cloudsmith-io/cloudsmith-cli-action@v1
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
      - name: Push to Cloudsmith
        run: |
          for file in dist/*.deb; do
            cloudsmith push deb michaeldcanady/odc/debian/nodistro "$file"
          done
